### ISSUE TITLE
[Request] Temporary solution for Crystal gathering.

### ISSUE THREAD

**Issue by Serfrost** [FFXIV-CombatReborn/GatherBuddyReborn#110]
As discussed on Discord, leaving a note for a reminder, simply giving the user an option to force-enable the Crystal Skills on every gathering node with some GP requirements would be more than enough for the time being. It would be the user's responsibility to disable Crystal-related skills when they wish to go gather other kinds of materials.

This would work as a temporary measure--until it's fully implemented, when you can gather crystals during node downtime.

This should solve #99 when added.

**Comment by lazyranma** [comment]
https://github.com/FFXIV-CombatReborn/GatherBuddyReborn/pull/137 should have solved this.
