### ISSUE TITLE
Yak T'el Spring Water:  Stuck on mid air

### ISSUE THREAD

**Issue by Wiratama23** [FFXIV-CombatReborn/GatherBuddyReborn#112]
there's a little of different height to reach the node that makes the nav confused and stop working. i propose to allow the user to update the landing location near it if a bug like this were to occur. Then after completing that node location, it takes longer time to generating the path.

**Comment by KrisaraMoon** [comment]
Yes, it gets stuck on the mount on this node because of the small mountain wall there.  Sometimes it'll dismount gather the node and then your character just stands there and does nothing else.  It says that navmesh cannot see the floor when mounted.
![Screenshot 2024-08-03 115515](https://github.com/user-attachments/assets/e3bee262-e948-4345-8296-ca4f13403762)

**Comment by AltinaXIV** [comment]
This also happens with "Bomb Ash"

**Comment by NostraThomas99** [comment]
Turn off experimental navigation and use an offset for the node instead.

**Comment by KrisaraMoon** [comment]
> Turn off experimental navigation and use an offset for the node instead.

I added an offset to the node and it still gets stuck.

**Comment by NostraThomas99** [comment]
Try again, then. It can take a few tries to find an offset that Vnavmesh agrees with.

**Comment by Reeses31** [comment]
> Turn off experimental navigation and use an offset for the node instead.

Sorry I am fairly new to the plugins and I know this is closed already but how do you use an offset for the node? I am having the same problem as well recently.

Thank you so much!

**Comment by Reeses31** [comment]
> > Turn off experimental navigation and use an offset for the node instead.
> 
> Sorry I am fairly new to the plugins and I know this is closed already but how do you use an offset for the node? I am having the same problem as well recently.
> 
> Thank you so much!

Scratch that, I've found the discord! I will check the fixes here. Thank you!
