### ISSUE TITLE
Gatherbuddy Reborn Teleporting not working

### ISSUE THREAD

**Issue by DarknesssX** [FFXIV-CombatReborn/GatherBuddyReborn#119]
Normally when clicking on the name of the item in the gatherables list it would teleport to the closest aetheryte. This is no longer happening, When i try to click the name on regular Gatherbuddy it does put down the marker and Teleport to the nearest aetheryte, But no longer on GBR.

**Comment by DarknesssX** [comment]
New update seems to have solved this

**Comment by Necr0fantasia** [comment]
Same for me

**Comment by NostraThomas99** [comment]
It's /extremely/ important that you restart your game after installing GatherBuddy and before installing GBR. Failing to do so will cause exactly this issue.

**Comment by DarknesssX** [comment]
Yeah, no i uninstalled both, Installed Gatherbuddy first > Restarted the Game and installed Gatherbuddy Reborn and im still having the same issue so this is incorrect something IS wrong
