### ISSUE TITLE
[REQUEST] Option for separate collectability cap if you don't have enough GP for a full rotation

### ISSUE THREAD

**Issue by cjmanca** [FFXIV-CombatReborn/GatherBuddyReborn#128]
When doing collectables for aethereal reduction, you often want to do a full GP rotation for 1000 on one node and then only 400 collectability with a 0 gp rotation on other nodes until you have enough GP to do a full rotation again. So an option for a separate collectability goal if not doing a full rotation would be nice.

**Comment by lazyranma** [comment]
Config > Auto-Gather > Collectables
Minimum GP for Gathering = 0
Minimum GP for using skill on collectibles = 1000
Collectibility score to reach before gathering = 1000
Gather instead losing the node = YES
Minimum collectibility score to reach before gathering on the last integrity point = 400

Works fine for me

**Comment by lazyranma** [comment]
Sorry, I only now fully understood your question. You want the collection to start after 400 collectability. It is impossible to set it up like that now, but in my opinion, one item with ~800 collectability gives several times more resources than one item with ~400 collectability. That is why I recommended such settings.

**Comment by cjmanca** [comment]
I was under the impression that you don't have any higher chance of getting aether sand between 400 and 999, so may as well stop at 400 if you're not hitting 1000

**Comment by lazyranma** [comment]
I can't be 100% sure about sands, but subjectively the chance to get it is higher, the higher the collectability. As for crystals, they definitely scale from collectability.
