### ISSUE TITLE
Teamcraft Import adds additional on each import.

### ISSUE THREAD

**Issue by GokaiSanyu** [FFXIV-CombatReborn/GatherBuddyReborn#133]
Tried using the import feature today, and I noticed something odd. Whenever I add an item and then delete it, rather than present the number as intended, it adds on to the original value.

An easy example would be to add a 300-piece gathering item. When you delete it on the list and import it again, instead of being 300, it is now 600.

**Comment by kszaso** [comment]
![image](https://github.com/user-attachments/assets/426452cd-7364-4a04-b20c-d08738defd01)
