### ISSUE TITLE
Re: Gatherbuddy Reborn Teleporting not working #119

### ISSUE THREAD

**Issue by DarknesssX** [FFXIV-CombatReborn/GatherBuddyReborn#135]
As stated before Teleport is not working when clicking on the gatherable item in the list, I removed both gatherbuddy and gatherbuddy reborn.

1. Installed Gatherbuddy normally first 
2. Rebooted the game
3. installed Gatherbuddy Reborn

Still having the same issue clicking on the gatherable item on the list DOES NOT activate the teleport to the aetheryte i have to click specifically on the name on the "Aetheryte" category in the list which was not how it was working and if i click on the item in normal Gatherbuddy THEN IT DOES TP. But due to it not working on Gatherbuddy Reborn Auto Gather does not want to work correctly. 

Please assist if im doing anything wrong here, or check to have this fixed.

**Comment by NostraThomas99** [comment]
You cannot use GatherBuddy and GatherBuddy Reborn at the same time. That's what's causing your problem. They use the same command/macro hooks and are entirely incompatible with each other.
