### ISSUE TITLE
Auto-Gather collects 1 more item than requested

### ISSUE THREAD

**Issue by lazyranma** [FFXIV-CombatReborn/GatherBuddyReborn#136]
When you ask Auto-Gather to collect X items it actually tries to collect X+1 items. It actually breaks auto-gathering of tressure maps.
AutoGather.Vars.cs:156
`                if (item.InventoryCount > item.Quantity)`
replace > with >=

**Comment by NostraThomas99** [comment]
Fixed in PR #141
