### ISSUE TITLE
[REQUEST] Ability to auto-turn in collectables

### ISSUE THREAD

**Issue by souleater205** [FFXIV-CombatReborn/GatherBuddyReborn#150]
Would be a nice feature if there was a way to auto turn in any collectables in inventory. Could do some settings like you turn in only when you have x amount of collectables or only when your inventory is full. If this is impossible or really wish to not implement it i think its understandable.

**Comment by NostraThomas99** [comment]
This is out of scope for GBR. Turning in collectibles is better handled by other plugins.
