### ISSUE TITLE
Auto-Gather Import adds the importet amount to the existing amount

### ISSUE THREAD

**Issue by maxrmax** [FFXIV-CombatReborn/GatherBuddyReborn#153]
Previously it didn't add but set (overwrote) the quantity with the imported quantity.
Now it adds the imported quantity on the current quantity resulting in numbers you don't want.
before pressing import
![image](https://github.com/user-attachments/assets/2f506221-527e-435c-bd44-9d6692888861)

after pressing import
![image](https://github.com/user-attachments/assets/080d20ec-773a-40d4-9fac-e6afc016c0d4)

expected values after import:
![image](https://github.com/user-attachments/assets/f8069d8c-33af-4520-a710-78abac59a850)

(2nd value unimportant for this case, was not imported and stayed as expected).

Additional i opened a request: #152 
In combination to that you could make multiple gather lists that don't interact with each others by changing the quantity through importing in different lists, making it more organized.

**Comment by NostraThomas99** [comment]
This is intended behavior in the live version. List quantities are handled separately in the test version, though. Feel free to to update and give it a try.
