### ISSUE TITLE
Auto-Gather not starting

### ISSUE THREAD

**Issue by baebypowder** [FFXIV-CombatReborn/GatherBuddyReborn#158]
Whenever I try to check off Enable for Auto-Gather it checks itself off and doesn't start
I have vnavmesh installed and enabled, it worked about a week or so ago but suddenly no longer works
![ffxiv_dx11_2024-08-03_17-13-15-ezgif com-optimize](https://github.com/user-attachments/assets/1257a020-20fb-485e-bf89-ec3c349699b7)

**Comment by NostraThomas99** [comment]
If you haven't already, try restarting your game. You can also try toggling the auto-gather function from the gather window instead of the main GBR window, it tends to work better.
