### ISSUE TITLE
[Help] Auto Materia Extraction - How does it work?

### ISSUE THREAD

**Issue by wolgnoy** [FFXIV-CombatReborn/GatherBuddyReborn#159]
Hi, I see the option for materia extraction, but when I enabled it, when auto gathering it does not extract when my spiritbond is full. I have YesAlready installed with the required option enabled as well. Is there something else I'm missing, or does it only happen at specified times?

**Comment by NostraThomas99** [comment]
Try updating to the testing version. It has some fixes for materia extraction that make it more reliable. To answer your question, though, you just need to enable the option in GBR and enable the proper bother option in YesAlready and it will extract before interacting with a node.

**Comment by wolgnoy** [comment]
Thank you for the hardwork!
