### ISSUE TITLE
[Bug[] GBR Thinks its stuck and flys into the distance

### ISSUE THREAD

**Issue by AltinaXIV** [FFXIV-CombatReborn/GatherBuddyReborn#161]
Certain nodes cause GBR to think its stuck and attempt to fly off the map with both experimental nav/stuck on and off. This has happened with acacia logs and Mythril Ore.

**Comment by NostraThomas99** [comment]
vnavmesh does that sometimes. Try using an offset.

**Comment by AltinaXIV** [comment]
Any chance you could explain how to add an offset?

**Comment by NostraThomas99** [comment]
There's a guide on how offsets work on the FAQ section of the Discord:
https://discord.com/channels/1064448004498653245/1242606544089120818/1266102185092055132
