### ISSUE TITLE
Auto-gatherer not gathering at all

### ISSUE THREAD

**Issue by dmxdwd** [FFXIV-CombatReborn/GatherBuddyReborn#166]
Everything seems enabled, wanted to gather Chamomile but as you can see, nothing is gathering. I'm just stuck in the harvesting menu.
![image](https://github.com/user-attachments/assets/d10a0ee5-8b2d-46c5-a085-432b62bae9a3)
![image](https://github.com/user-attachments/assets/db38efef-ecc5-40fc-9095-a31b237cc67a)

I'm not sure what the issue would be - one second it was working, then it suddenly wasnt working when I came back to try and do levels. All the auto movement is working but it still requires manual clicking by me.

**Comment by lrequena** [comment]
Seems like the same problem I'm having:

#165

**Comment by dmxdwd** [comment]
I've tried a few vnav options like reload and rebuild but none of these have worked so far. I do have a few plugins already installed

**Comment by dmxdwd** [comment]
So same thing for me where some things seems to be able to collect but some don't. Right now I'm able to harvest Laurel in Southern Thanalan. It's so bizarre

**Comment by dmxdwd** [comment]
Alright I might just be a moron, LOL. Under "Config" -> "Auto Gather" -> "Gathering Actions" -> "Bountiful Yield" the "Use BYII" was ticked, meaning it was only going to work if I had the GP to run bountiful yield. 

I certainly don't remember switching on this feature which is why its puzzled me, regardless this is solved.

**Comment by lrequena** [comment]
I've just debugged the code... it seems the maximum GP shouldn't be -1... and it was -1 for me...
Also it was set to -1 for some other actions... I've adjusted them and now it's working and using the actions correctly!

![image](https://github.com/user-attachments/assets/e57b24f0-0a13-4213-bdc3-3b739c34759d)
