### ISSUE TITLE
Crystal Farming

### ISSUE THREAD

**Issue by Twilex** [FFXIV-CombatReborn/GatherBuddyReborn#169]
Hello, 

I created a list in Teamcraft with all 6 crystals, gave each of them a max of 9999, and imported it into GBR. The issue is, once you hit 9999 of whatever crystal you are gathering, and you're in the middle of a node (say 2/4) it gets hung up, and won't leave the node because your inventory is full. It will just sit there trying to spam gather forever. Sorry if this is already a known issue.

**Comment by NostraThomas99** [comment]
This is known and probably won't be fixed any time soon. Just keep a closer eye on your inventory while gathering items that have a cap.
