### ISSUE TITLE
crystal gather error

### ISSUE THREAD

**Issue by akazhuk** [FFXIV-CombatReborn/GatherBuddyReborn#171]
I set it  to collect Fire Crystal, but he collected Fire Shard instead.

**Comment by NostraThomas99** [comment]
Need more info, /xllog output, debug tab info, etc.

**Comment by akazhuk** [comment]
![image](https://github.com/user-attachments/assets/fe5974f5-cc4a-45df-88d2-6a8f4337149f)

**Comment by NostraThomas99** [comment]
All this tells me is you're probably using a *very* out of date version. Please make sure you're using the live version from the repo.
