### ISSUE TITLE
[Bug] advanced unstuck doesn't cancel vnavmesh path and therefore remains in place when trying to move backwards

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/GatherBuddyReborn#172]
^

**Comment by NostraThomas99** [comment]
This is intentional. Canceling a pathing task while vnavmesh is generating a path will cause vnavmesh to lock up entirely in some situations. Advanced unstuck is intended to 'trick' vnav into generating a path when it's not able to normally.
