### ISSUE TITLE
not teleporting with idle enable 

### ISSUE THREAD

**Issue by Shbounab** [FFXIV-CombatReborn/GatherBuddyReborn#174]
maybe i am missing something but enabling teleport to home when idle or waiting for note, just stands still and wont teleport

**Comment by emi-rii** [comment]
This is happening to me too, occasionally the status will say I need to restart the game. Clicking on items in the auto-gather window also does not initiate a teleport.

**Comment by NostraThomas99** [comment]
"Go Home When Idle" requires Lifestream to be installed and enabled.
