### ISSUE TITLE
Forced transfer to home when in crossworld party

### ISSUE THREAD

**Issue by captaincbr1** [FFXIV-CombatReborn/GatherBuddyReborn#177]
I was in a crossworld party with my static about to raid when I installed GBR. When I started it up, it instantly went logged out and tried to go back to my home world. Not sure if this is intended or not

**Comment by NostraThomas99** [comment]
This is likely caused by the "Go Home When Idle" option. It uses the "/li auto" command to take you home instead of idling at the node. If you're on another server/datacenter this command would take you back to your home server. This option is configurable on the Config tab.
