### ISSUE TITLE
botanist dont work

### ISSUE THREAD

**Issue by Sstronget** [FFXIV-CombatReborn/GatherBuddyReborn#183]
When I play botanist  autogather doesn't work. only works with miner

**Comment by Hakkon7** [comment]
also doesn't work for me

**Comment by NostraThomas99** [comment]
This is almost always caused by this:

https://discord.com/channels/1064448004498653245/1241289871373504576/1265696526941028392

**Comment by Hakkon7** [comment]
I cant see the discord link because I'm not in the discord...
