### ISSUE TITLE
Navigation constantly updated to different nodes, effectively stuck in limbo

### ISSUE THREAD

**Issue by StarkITA** [FFXIV-CombatReborn/GatherBuddyReborn#213]
I have noticed while trying to gather Titanium Ore, that navigation will start to swap target every second or so, effectively placing the character in a limbo, in between all the nodes, unable to reach any

**Comment by lazyranma** [comment]
Update GBR to the last version ant try again.

**Comment by StarkITA** [comment]
I think it has been fixed. Will close!
