### ISSUE TITLE
Auto gather

### ISSUE THREAD

**Issue by tianyuanhime** [FFXIV-CombatReborn/GatherBuddyReborn#218]
I am a player from China.When I was collecting Fine Silver Ore in Shaaloani (Yawtanane Grasslands), the Auto Gather was not working properly, and the character just stood there without actively approaching the collection point. I have tried to adjust the corresponding coordinates within the set Locations, but it still does not work properly
As shown in the figure, it keeps jumping back and forth between "moving to a closer node" and "generating path"
![1](https://github.com/user-attachments/assets/080c404b-4c9f-464e-bbed-8eaea64076ff)
![2](https://github.com/user-attachments/assets/32ac8673-92ea-4e46-a698-b2fe96651e94)
![3](https://github.com/user-attachments/assets/3fc4183a-9171-4e54-a469-878774dca3f2)

**Comment by lazyranma** [comment]
1) What version number are you using?
2) Collect logs from GatherBuddyReborn and vnavmesh via /xllog (level Debug+).

**Comment by NostraThomas99** [comment]
The only time I've seen this is if you set your node offset outside of the interaction range for the node. Your offset *must* be within 3 yalms of the node or you'll end up in a loop like this.

**Comment by tianyuanhime** [comment]
> 1. 您使用的是什么版本？
> 2. 通过 /xllog (级别 Debug+) 从 GatherBuddyReborn 和 vnavmesh 收集日志。

1.v7.0.3.0，I have tried downloading the latest version 7.2.2.2, but it seems that it cannot be enabled due to version incompatibility
2.This malfunction occurred at 10:38, and I'm not sure if this screenshot can identify the key issue
Finally, that was the modification I made to the Locations settings of Fine Silver Ore, and I'm not sure if this modification had any effect

![5](https://github.com/user-attachments/assets/65d048d6-aeac-4ecc-9eb7-863f1591fad0)
![6](https://github.com/user-attachments/assets/d664f18c-3881-4a05-8e1d-e0e5d3ec6058)
![7](https://github.com/user-attachments/assets/91b83ecb-2cba-477f-987b-6a3237881dc6)

**Comment by lazyranma** [comment]
The issue with <0, 0, 0,> vector was fixed in the latest version, please check it out.

**Comment by NostraThomas99** [comment]
Chinese clients are not supported. There's nothing I can do if you won't use the most recent version. I can support a version from 3 months ago.
