### ISSUE TITLE
Fine Silver Ore

### ISSUE THREAD

**Issue by tayiahott** [FFXIV-CombatReborn/GatherBuddyReborn#222]
the auto gather will some of the time will go to the node get off the mount right in front of the node but it won't interact with the node and if i click on the node it will work i dont get why this one node is doing this and  i can't seem to find a way to fix it

**Comment by NostraThomas99** [comment]
This is almost always caused by your offset being too far from the node. If your offset is more than 3 yalms from the node GBR won't interact with the node. Make sure your offset is built in such a way that it always results in you being less than 3 yalms from the node once you're off your mount.
