### ISSUE TITLE
timed nodes suddenly won't gather

### ISSUE THREAD

**Issue by amaraame** [FFXIV-CombatReborn/GatherBuddyReborn#250]
It'll send character to the node, open then close it and set the list to idle, giving me the list complete noise. Only seems to be a problem with timed nodes

**Comment by wwwwowowdjasdfj** [comment]
Same issue, occurring only after the most recent update from earlier today. Everything was flawless prior to that.

**Comment by amaraame** [comment]
> config presets> collectable actions set maximum GP 2000, you will be fine

Tried it, worked. tyvm
