### ISSUE TITLE
constant error

### ISSUE THREAD

**Issue by Shadow35a** [FFXIV-CombatReborn/GatherBuddyReborn#252]
I am receiving the following error when trying to collect either a miner or botanist collectible node  "Unable to pick a collectability increasing action to use. Make sure that at least one of the collectable actions is enabled." No changes have been made since yesterday when it was working with no issues. GP = 900, gear is repaired, all config remain unchanged. Thanks

**Comment by Shi974** [comment]
Same as above. Everything was fine before the update and now auto-gather does not work with collectables anymore. I have the same error message.

And with regular nodes, the buffs are not used but it auto-gathers.

**Comment by NostraThomas99** [comment]
There's a bug with the default settings migration causing your maximum GP settings to get set to 0. Adjust these in your config preset and it should solve the problem.

**Comment by Shadow35a** [comment]
> There's a bug with the default settings migration causing your maximum GP settings to get set to 0. Adjust these in your config preset and it should solve the problem.

![GP](https://github.com/user-attachments/assets/b10462b1-09db-44b6-8b0b-984b42818577)

The config presets are set as per the image, there isn't a maximum GP setting (I've also checked the Config + Config Presets) and havent been able to find this field. Any help would be appreciated
