### ISSUE TITLE
Issue trying to farm cobalt ore

### ISSUE THREAD

**Issue by Luysita** [FFXIV-CombatReborn/GatherBuddyReborn#259]
I'm having an issue when I try to gather cobalt ore, it's generating a path to the opposite side, and when does the unstuck method, it just stops and generates the same path again

**Comment by NostraThomas99** [comment]
Use offsets to correct for vnavmesh issues:
https://discord.com/channels/1064448004498653245/1242606544089120818/1266102185092055132
