### ISSUE TITLE
Bountiful Yield II

### ISSUE THREAD

**Issue by PotatoGary** [FFXIV-CombatReborn/GatherBuddyReborn#260]
Since there is no "Unable" option in the config section, when I am trying to gether crystals, it always use Bountiful Yield II when there is 100GP which leads the other action (like The Giving Land and The Twelve's Bounty) never been used unless it is revisit, is there any way that I can disable this action? Or like set at least over 450GP to use?

**Comment by lazyranma** [comment]
See "Config Presets" tab, you can disable actions there or set minimum/maximum GP.

**Comment by PotatoGary** [comment]
Just realised it is sync with Bountiful Yield 1, it works now, thank you
