### ISSUE TITLE
[Request] Food option

### ISSUE THREAD

**Issue by amaraame** [FFXIV-CombatReborn/GatherBuddyReborn#261]
would it be possible to add a food option to auto-gather list? So it wouldn't go off for anything i gather but for a specific list, it'll check food buff and use food prior to gathering as needed. Sorry if this already exists as an option, i haven't seen anything for it.

**Comment by lazyranma** [comment]
You can set food for different node types or item types or item levels under Config Presets tab.

**Comment by amaraame** [comment]
> You can set food for different node types or item types or item levels under Config Presets tab.

oh ok, i'll give that a shot. tyvm
