### ISSUE TITLE
Gather Group doesnt work

### ISSUE THREAD

**Issue by aSkterisk1** [FFXIV-CombatReborn/GatherBuddyReborn#262]
Selecting any item from gatherable and fish tab to gather group does not appear on gather window most likely because auto-gather overwrite the tab

![{9FF615E2-39CE-4C32-820C-4644CA1E8927}](https://github.com/user-attachments/assets/22e7b494-dece-45c0-99c9-cf191dee583d)

![{CE968F53-31E6-4059-BCEF-F2B2C879AF8F}](https://github.com/user-attachments/assets/755664b5-f370-40e4-ae46-d26748e4ccec)

![{80E3B6A8-9BA2-4940-80BF-81B9A43B62B0}](https://github.com/user-attachments/assets/f43292c8-afdb-49c2-a4df-93725432e2a1)

**Comment by lazyranma** [comment]
Gather groups never appeared on the gather window; only alarms and gather window presets did. And gather window presets became auto-gather lists.

**Comment by aSkterisk1** [comment]
If that's the case, not being able to add fish on the gather window is an unnecessary con for the plugin
