### ISSUE TITLE
[Feature Request] Improved Nald'thal/Nophica's Tidings Settings

### ISSUE THREAD

**Issue by ghptg** [FFXIV-CombatReborn/GatherBuddyReborn#263]
Currently, the settings for Tidings allow use only on first step, GP range, boon chance range and minimum node integrity. 

When I'm trying to determine if Tidings is worth it, I compare the GP spent and expected items gained. To do so, I take the boon chance and multiply it by node integrity. That gives me the yield bonus for the 200 GP spent. Knowing this number allows me to determine if this is better than just spamming Bountiful.

This leads me to my feature request. Can we have a setting where Tidings is set based on expected yield, similar to `Minimum Yield Bonus` on Bountiful? It would take multiply node integrity by boon chance, and compare to this setting. 

If it's a 4 integrity node, and boon chance is 75%, we can expect 3 extra yield. Considering the GP spent, Bountiful is more than likely better to use.

On the other hand, an 8 integrity node having a boon chance of 75% should yield us 6 more items. This is more efficient than Bountiful, so should be a first step action.

Unfortunately, the current settings do not allow this. You can set boon chance range and minimum node integrity, but yield is a better number to use.

**Comment by lazyranma** [comment]
Well, it's just one case. But what if the node has a huge yield bonus, so it's better to use King's and Solid / Ageless? And what if you are not at full GP? Is it better to dump all GP on the first node, hoping for Revising proc, or keep GP for King's or The Giving Land?
I think it's impossible to get the "most optimal rotation" right not implementing a full rotation solver like https://catgirl-jade.github.io/nophicas-tidings/ and even that alone is not enough.

**Comment by lazyranma** [comment]
Actually, I think your request may be solved by adding node integrity into the match section (where the node types are) of config presets.

**Comment by ghptg** [comment]
> Well, it's just one case. But what if the node has a huge yield bonus, so it's better to use King's and Solid / Ageless? And what if you are not at full GP? Is it better to dump all GP on the first node, hoping for Revising proc, or keep GP for King's or The Giving Land? I think it's impossible to get the "most optimal rotation" right without implementing a full rotation solver like https://catgirl-jade.github.io/nophicas-tidings/ and even that alone is not enough.

Totally understandable, and honestly, would be a very minor item/hour improvement. Thanks for the reply. Here's hoping my next feature request makes sense, or I code it myself (hmm... autodiscard list?)
