### ISSUE TITLE
Auto enable on login toggle

### ISSUE THREAD

**Issue by MillionPotatoes** [FFXIV-CombatReborn/GatherBuddyReborn#270]
Would it be possible to add a toggle under general settings which enables/disables the GBR auto-gather status on character login?

Current behavior is to start GBR with auto-gather disabled on login.

Desirable behavior would be to choose whether GBR starts enabled (green status line in the window) or disabled (white status line in the window).

_NB this entire thing is a workaround for the random crashes introduced in 7.1. A .bat script relaunches the ffxiv exefile on crash. The other plugin (not named for tact purposes) logs in the toon. Would be super nice if GBR could start enabled without manual input; or resorting to convoluted .lua scripts, or AHK workarounds._

Thank you!

**Comment by NostraThomas99** [comment]
I have no plans to add anything like this. GBR is not designed to be used while AFK and I don't want to add any features that encourage that behavior.

If you absolutely must use GBR while AFK, multiple plugins will let you run slash commands on login. GBR can be started via command using "/gbr auto on".
