### ISSUE TITLE
not auto gathering collectibles

### ISSUE THREAD

**Issue by JennyCupcakes** [FFXIV-CombatReborn/GatherBuddyReborn#278]
My char will walk up to the collectible node location but will not do anything else to it. What am I doing wrong? It used to work on my old PC but since I built a new one I have not been able to get it to work since then. 

https://github.com/user-attachments/assets/a9b4c21e-21ec-4255-b972-5cb10ad8a86f

**Comment by NostraThomas99** [comment]
I can't troubleshoot unless you provide more information. Check /xllog for errors, look at the debug tab for state information, etc.

**Comment by JennyCupcakes** [comment]
I currently don't see any error regarding GBR, the collectible section is not there for me anymore..

**Comment by JennyCupcakes** [comment]
I got it to work! Sorry about that!
