### ISSUE TITLE
"legendary mineral deposits" suggestions

### ISSUE THREAD

**Issue by warknight1211** [FFXIV-CombatReborn/GatherBuddyReborn#40]
Can you improve the collection method?
For example: Collect "Ilmenite" from 8:00 to 10:00 Eorzea time. After the collection is completed, the character will still patrol between the collection points where "Ilmenite" may appear.

If the current version of the plugin itself can solve this problem, please tell me in detail how to set it in the plugin, thank you.

If the current version of the plugin cannot solve it, I have the following improvement suggestions:
1. Check the game log, when the collection is completed, pause and wait for the next collection point to arrive, or teleport to the next collection point according to Eorzea time.

**Comment by middleeast856** [comment]
This is also happening to me for 2 dawntrail leg nodes fine silver ore and ipe log. I would also like to mention that I just sit at the aetheryte leynode pyro for the leg node blackseed cotton ball until its time for the next node which is harmonite ore in the same zone at aetheryte leynode aero.
