### ISSUE TITLE
Error installing Plugin after adding in Experimental 

### ISSUE THREAD

**Issue by DarknesssX** [FFXIV-CombatReborn/GatherBuddyReborn#41]
![image](https://github.com/FFXIV-CombatReborn/GatherBuddyReborn/assets/1254137/15cce5c6-24c9-400c-83a7-e8a202cac965)
as suggested Reboot has been done but same error pops up

**Comment by NostraThomas99** [comment]
You must've missed the big red text from Dalamud saying it hasn't been updated for Dawntrail yet.

**Comment by DarknesssX** [comment]
does not show it on my screen
