### ISSUE TITLE
[Request] Gather window interaction toggle fix

### ISSUE THREAD

**Issue by naTlatsyrC** [FFXIV-CombatReborn/GatherBuddyReborn#64]
Under the config settings it has a toggle to enable or disable the interaction with the gather window.
![image](https://github.com/user-attachments/assets/8b3b27a3-abd9-4b6d-8f5c-9b12d0f1fedd)

However this doesn't work currently and I wanted to ask if it was possible this could be fixed as I adore the navigation to nodes that GBR provides, but I prefer Pandora Gather (from Pandora's Box plugin) for gathering the material from the node due to it supporting popping crystal gathering abilities and is a little bit faster between actions.

Thanks for all your hard work!!

**Comment by maxrmax** [comment]
Hey, i got the solution for you.
Go into the GBR config and disable all actions. 
Ignore the advanced tab.

Now in Pandora -> Other , i use this:
Pandora Quick Gather
- Disable Starting Buff
- Enable Pandora Gathering
- Remember Items between nodes
- Whatever buff i want to use.

If you uncheck the box, it stops gathering. Better quick gathering.

GBR will start the gathering the item you want, but pandora will gather it the way you want (with buffs).

So far i had no issues and it worked flawlessly so far. (Exception: Diadem)
