### ISSUE TITLE
fix navigation so auto gather would not get stuck on rocks

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/GatherBuddyReborn#69]
sometimes auto gather fails to interact with node because game cannot get character off the mount
![ffxiv_dx11_NnubXj13ON](https://github.com/user-attachments/assets/d89832fc-8e50-43ab-8c71-2a6788d82f70)

i would suggest to add another anti-stuck measure of moving a little forward, or in some random direction, to get navmesh to approach the node in different position. BTW same can be done if navmesh fails to build a path for some reason.

**Comment by NostraThomas99** [comment]
GBR cannot move the character without navmesh. If navmesh is refusing to move the best you can do is let auto-unstuck take care of it.
