### ISSUE TITLE
[REQUEST] maybe a way to import the materials from artisan crafting list?

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/GatherBuddyReborn#72]

**Comment by NostraThomas99** [comment]
GBR already supports Teamcraft importing. It's looking for a list of item names with quantities like Teamcraft would export. Artisan should be able to provide the same info or you can use Teamcraft as an intermediary.

**Comment by K0shachiyamyatA** [comment]
ah okay
