### ISSUE TITLE
Auto-Gatherer doesn't work

### ISSUE THREAD

**Issue by Animaspop** [FFXIV-CombatReborn/GatherBuddyReborn#73]
I am unable to use Auto-Gatherer with vnavmesh installed and support for flying enabled.

![image_2024-07-21_165443018](https://github.com/user-attachments/assets/c2e18b4d-2b08-4f59-8e96-18417f1a0cdc)

Debug gives the following information:

![image](https://github.com/user-attachments/assets/0074d035-8f47-41bd-a897-bc52574325b2)

Is there any documentation on how the Auto-gatherer functions?

**Comment by K0shachiyamyatA** [comment]
you didn't set the quanity of items needed
