### ISSUE TITLE
Mount use interrupted

### ISSUE THREAD

**Issue by StarkITA** [FFXIV-CombatReborn/GatherBuddyReborn#77]
Often happens that GBR has some issues with using a mount. It happens both underwater and on ground. It stays on the spot, tries to use mount repeatedly, but *for some reason* it's always interrupted.

I attach the debug screen, if it can be of some help.

![image](https://github.com/user-attachments/assets/bdfaf8c9-a000-4462-8e41-5f47fed45a8e)

**Comment by NostraThomas99** [comment]
This is almost always caused by having the Pandora's Box feature for "Auto-Mount after gathering" enabled. You should disable all Pandora Gathering related features while using GBR.

**Comment by StarkITA** [comment]
Thanks! You can close the issue :)
