### ISSUE TITLE
Auto use Cordial if in inventory and GP < treshold

### ISSUE THREAD

**Issue by logicmoon** [FFXIV-CombatReborn/GatherBuddyReborn#79]
Would it be possible to add an option to automatically use Cordial or Hi-Cordial if they are available in the player's inventory and GP fall below a certain threshold? Thank you for your work on this.

**Comment by K0shachiyamyatA** [comment]
just install pandora box

**Comment by logicmoon** [comment]
Thank you, this solves the issue for me
