### ISSUE TITLE
Issue waiting at waypoint.

### ISSUE THREAD

**Issue by fraterns** [FFXIV-CombatReborn/GatherBuddyReborn#80]
With auto gather, the majority of the time it will teleport to the new zone and then move to the set waypoint flag and if the node is not up, sit and wait at the flag until the node appears then move to it and collect.  Often though, once it gets to the flags position even though the node is not up yet, it routes from possible spawning node to the next, over and over until the node finally appears. I assume that this is not desired behavior. I have played with the node ignore distance but have not seen any change in this behavior. Nor can I find a commonality as to when it will start it's rapid node rotation. The only common thing so far that it seems to more easily get stuck, particularly if it's among trees and it doesn't seem to be able to recover from that. Any ideas or suggestions in how to determine what is going on, or how to approach fixing this? Is there any additional info I can provide?

**Comment by NostraThomas99** [comment]
Working as designed. Adjust the "Timed Node Precog" setting if you want to show up exactly on time.

**Comment by fraterns** [comment]
Thank you for responding. That will avoid the behavior.

Is there a specific trigger that makes this occur though? 

As an example, collecting Rarefied Acasia Bark in Pyariyoanaan Plain, when arriving before the node pops. Sometimes it will navigate to the flag at 31.67 20.43 and then wait until the node pops before moving further, sometimes though it will immediately rotate/travel to the three possible spawn locations in a loop until the node pops.

What triggers the diferent behaviors?

**Comment by NostraThomas99** [comment]
"Far Node Filter Distance" is what determines that as well as how far apart the particular nodes are. If GBR can "see" the nodes it wants to see from where it's standing it won't move, if it's out of range of the nodes it'll get within range to check if they're available.
