### ISSUE TITLE
Incorrect usage of solid reason/ageless words.

### ISSUE THREAD

**Issue by AnonLoid** [FFXIV-CombatReborn/GatherBuddyReborn#82]
GBR using solid/age wrong. It use age/solid 2 times, even if after first usage player get eureka moment proc. GBR just skips first proc of eureka if it happens, but USE eureka if its only one action, that is left for additional gathering attempts.

**Comment by leothelion4953** [comment]
I just submitted a pull request (#83) on this as I observed the same issue.

**Comment by AnonLoid** [comment]
Fixed on 7.01.0.9
